<?php
/**
 * DataConsentDetailsDto
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  MyDataMyConsent
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MyDataMyConsent\Model;

use \ArrayAccess;
use \MyDataMyConsent\ObjectSerializer;

/**
 * DataConsentDetailsDto Class Doc Comment
 *
 * @category Class
 * @package  MyDataMyConsent
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class DataConsentDetailsDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DataConsentDetailsDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'requester' => '\MyDataMyConsent\Model\DataConsentRequesterDto',
        'location' => 'string',
        'personal_info_requested' => 'bool',
        'documents' => 'int',
        'financial_accounts' => 'int',
        'transaction_id' => 'string',
        'ip_address' => 'string',
        'description' => 'string',
        'purpose_code' => 'string',
        'purpose_link' => 'string',
        'agreement_id' => 'string',
        'data_life_unit' => '\MyDataMyConsent\Model\DataLifeUnit',
        'data_life_value' => 'int',
        'data_fetch_frequency_unit' => '\MyDataMyConsent\Model\DataFetchFrequencyUnit',
        'data_fetch_frequency_unit_value' => 'int',
        'data_fetch_type' => '\MyDataMyConsent\Model\DataFetchType',
        'status' => '\MyDataMyConsent\Model\DataConsentStatus',
        'approved_at_utc' => '\DateTime',
        'rejected_at_utc' => '\DateTime',
        'expires_at_utc' => '\DateTime',
        'requested_at_utc' => '\DateTime',
        'requested_financial_accounts' => '\MyDataMyConsent\Model\DataConsentRequestedAccountDto[]',
        'requested_documents' => '\MyDataMyConsent\Model\DataConsentRequestedDocumentDto[]',
        'requested_health_data' => '\MyDataMyConsent\Model\DataConsentRequestedDocument[]',
        'requested_identity_details' => '\MyDataMyConsent\Model\JsonSchema'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'requester' => null,
        'location' => null,
        'personal_info_requested' => null,
        'documents' => 'int32',
        'financial_accounts' => 'int32',
        'transaction_id' => null,
        'ip_address' => null,
        'description' => null,
        'purpose_code' => null,
        'purpose_link' => null,
        'agreement_id' => 'uuid',
        'data_life_unit' => null,
        'data_life_value' => 'int32',
        'data_fetch_frequency_unit' => null,
        'data_fetch_frequency_unit_value' => 'int32',
        'data_fetch_type' => null,
        'status' => null,
        'approved_at_utc' => 'date-time',
        'rejected_at_utc' => 'date-time',
        'expires_at_utc' => 'date-time',
        'requested_at_utc' => 'date-time',
        'requested_financial_accounts' => null,
        'requested_documents' => null,
        'requested_health_data' => null,
        'requested_identity_details' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'requester' => 'requester',
        'location' => 'location',
        'personal_info_requested' => 'personalInfoRequested',
        'documents' => 'documents',
        'financial_accounts' => 'financialAccounts',
        'transaction_id' => 'transactionId',
        'ip_address' => 'ipAddress',
        'description' => 'description',
        'purpose_code' => 'purposeCode',
        'purpose_link' => 'purposeLink',
        'agreement_id' => 'agreementId',
        'data_life_unit' => 'dataLifeUnit',
        'data_life_value' => 'dataLifeValue',
        'data_fetch_frequency_unit' => 'dataFetchFrequencyUnit',
        'data_fetch_frequency_unit_value' => 'dataFetchFrequencyUnitValue',
        'data_fetch_type' => 'dataFetchType',
        'status' => 'status',
        'approved_at_utc' => 'approvedAtUtc',
        'rejected_at_utc' => 'rejectedAtUtc',
        'expires_at_utc' => 'expiresAtUtc',
        'requested_at_utc' => 'requestedAtUtc',
        'requested_financial_accounts' => 'requestedFinancialAccounts',
        'requested_documents' => 'requestedDocuments',
        'requested_health_data' => 'requestedHealthData',
        'requested_identity_details' => 'requestedIdentityDetails'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'requester' => 'setRequester',
        'location' => 'setLocation',
        'personal_info_requested' => 'setPersonalInfoRequested',
        'documents' => 'setDocuments',
        'financial_accounts' => 'setFinancialAccounts',
        'transaction_id' => 'setTransactionId',
        'ip_address' => 'setIpAddress',
        'description' => 'setDescription',
        'purpose_code' => 'setPurposeCode',
        'purpose_link' => 'setPurposeLink',
        'agreement_id' => 'setAgreementId',
        'data_life_unit' => 'setDataLifeUnit',
        'data_life_value' => 'setDataLifeValue',
        'data_fetch_frequency_unit' => 'setDataFetchFrequencyUnit',
        'data_fetch_frequency_unit_value' => 'setDataFetchFrequencyUnitValue',
        'data_fetch_type' => 'setDataFetchType',
        'status' => 'setStatus',
        'approved_at_utc' => 'setApprovedAtUtc',
        'rejected_at_utc' => 'setRejectedAtUtc',
        'expires_at_utc' => 'setExpiresAtUtc',
        'requested_at_utc' => 'setRequestedAtUtc',
        'requested_financial_accounts' => 'setRequestedFinancialAccounts',
        'requested_documents' => 'setRequestedDocuments',
        'requested_health_data' => 'setRequestedHealthData',
        'requested_identity_details' => 'setRequestedIdentityDetails'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'requester' => 'getRequester',
        'location' => 'getLocation',
        'personal_info_requested' => 'getPersonalInfoRequested',
        'documents' => 'getDocuments',
        'financial_accounts' => 'getFinancialAccounts',
        'transaction_id' => 'getTransactionId',
        'ip_address' => 'getIpAddress',
        'description' => 'getDescription',
        'purpose_code' => 'getPurposeCode',
        'purpose_link' => 'getPurposeLink',
        'agreement_id' => 'getAgreementId',
        'data_life_unit' => 'getDataLifeUnit',
        'data_life_value' => 'getDataLifeValue',
        'data_fetch_frequency_unit' => 'getDataFetchFrequencyUnit',
        'data_fetch_frequency_unit_value' => 'getDataFetchFrequencyUnitValue',
        'data_fetch_type' => 'getDataFetchType',
        'status' => 'getStatus',
        'approved_at_utc' => 'getApprovedAtUtc',
        'rejected_at_utc' => 'getRejectedAtUtc',
        'expires_at_utc' => 'getExpiresAtUtc',
        'requested_at_utc' => 'getRequestedAtUtc',
        'requested_financial_accounts' => 'getRequestedFinancialAccounts',
        'requested_documents' => 'getRequestedDocuments',
        'requested_health_data' => 'getRequestedHealthData',
        'requested_identity_details' => 'getRequestedIdentityDetails'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['requester'] = $data['requester'] ?? null;
        $this->container['location'] = $data['location'] ?? null;
        $this->container['personal_info_requested'] = $data['personal_info_requested'] ?? null;
        $this->container['documents'] = $data['documents'] ?? null;
        $this->container['financial_accounts'] = $data['financial_accounts'] ?? null;
        $this->container['transaction_id'] = $data['transaction_id'] ?? null;
        $this->container['ip_address'] = $data['ip_address'] ?? null;
        $this->container['description'] = $data['description'] ?? null;
        $this->container['purpose_code'] = $data['purpose_code'] ?? null;
        $this->container['purpose_link'] = $data['purpose_link'] ?? null;
        $this->container['agreement_id'] = $data['agreement_id'] ?? null;
        $this->container['data_life_unit'] = $data['data_life_unit'] ?? null;
        $this->container['data_life_value'] = $data['data_life_value'] ?? null;
        $this->container['data_fetch_frequency_unit'] = $data['data_fetch_frequency_unit'] ?? null;
        $this->container['data_fetch_frequency_unit_value'] = $data['data_fetch_frequency_unit_value'] ?? null;
        $this->container['data_fetch_type'] = $data['data_fetch_type'] ?? null;
        $this->container['status'] = $data['status'] ?? null;
        $this->container['approved_at_utc'] = $data['approved_at_utc'] ?? null;
        $this->container['rejected_at_utc'] = $data['rejected_at_utc'] ?? null;
        $this->container['expires_at_utc'] = $data['expires_at_utc'] ?? null;
        $this->container['requested_at_utc'] = $data['requested_at_utc'] ?? null;
        $this->container['requested_financial_accounts'] = $data['requested_financial_accounts'] ?? null;
        $this->container['requested_documents'] = $data['requested_documents'] ?? null;
        $this->container['requested_health_data'] = $data['requested_health_data'] ?? null;
        $this->container['requested_identity_details'] = $data['requested_identity_details'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets requester
     *
     * @return \MyDataMyConsent\Model\DataConsentRequesterDto|null
     */
    public function getRequester()
    {
        return $this->container['requester'];
    }

    /**
     * Sets requester
     *
     * @param \MyDataMyConsent\Model\DataConsentRequesterDto|null $requester requester
     *
     * @return self
     */
    public function setRequester($requester)
    {
        $this->container['requester'] = $requester;

        return $this;
    }

    /**
     * Gets location
     *
     * @return string|null
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * Sets location
     *
     * @param string|null $location location
     *
     * @return self
     */
    public function setLocation($location)
    {
        $this->container['location'] = $location;

        return $this;
    }

    /**
     * Gets personal_info_requested
     *
     * @return bool|null
     */
    public function getPersonalInfoRequested()
    {
        return $this->container['personal_info_requested'];
    }

    /**
     * Sets personal_info_requested
     *
     * @param bool|null $personal_info_requested personal_info_requested
     *
     * @return self
     */
    public function setPersonalInfoRequested($personal_info_requested)
    {
        $this->container['personal_info_requested'] = $personal_info_requested;

        return $this;
    }

    /**
     * Gets documents
     *
     * @return int|null
     */
    public function getDocuments()
    {
        return $this->container['documents'];
    }

    /**
     * Sets documents
     *
     * @param int|null $documents documents
     *
     * @return self
     */
    public function setDocuments($documents)
    {
        $this->container['documents'] = $documents;

        return $this;
    }

    /**
     * Gets financial_accounts
     *
     * @return int|null
     */
    public function getFinancialAccounts()
    {
        return $this->container['financial_accounts'];
    }

    /**
     * Sets financial_accounts
     *
     * @param int|null $financial_accounts financial_accounts
     *
     * @return self
     */
    public function setFinancialAccounts($financial_accounts)
    {
        $this->container['financial_accounts'] = $financial_accounts;

        return $this;
    }

    /**
     * Gets transaction_id
     *
     * @return string|null
     */
    public function getTransactionId()
    {
        return $this->container['transaction_id'];
    }

    /**
     * Sets transaction_id
     *
     * @param string|null $transaction_id transaction_id
     *
     * @return self
     */
    public function setTransactionId($transaction_id)
    {
        $this->container['transaction_id'] = $transaction_id;

        return $this;
    }

    /**
     * Gets ip_address
     *
     * @return string|null
     */
    public function getIpAddress()
    {
        return $this->container['ip_address'];
    }

    /**
     * Sets ip_address
     *
     * @param string|null $ip_address ip_address
     *
     * @return self
     */
    public function setIpAddress($ip_address)
    {
        $this->container['ip_address'] = $ip_address;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets purpose_code
     *
     * @return string|null
     */
    public function getPurposeCode()
    {
        return $this->container['purpose_code'];
    }

    /**
     * Sets purpose_code
     *
     * @param string|null $purpose_code purpose_code
     *
     * @return self
     */
    public function setPurposeCode($purpose_code)
    {
        $this->container['purpose_code'] = $purpose_code;

        return $this;
    }

    /**
     * Gets purpose_link
     *
     * @return string|null
     */
    public function getPurposeLink()
    {
        return $this->container['purpose_link'];
    }

    /**
     * Sets purpose_link
     *
     * @param string|null $purpose_link purpose_link
     *
     * @return self
     */
    public function setPurposeLink($purpose_link)
    {
        $this->container['purpose_link'] = $purpose_link;

        return $this;
    }

    /**
     * Gets agreement_id
     *
     * @return string|null
     */
    public function getAgreementId()
    {
        return $this->container['agreement_id'];
    }

    /**
     * Sets agreement_id
     *
     * @param string|null $agreement_id agreement_id
     *
     * @return self
     */
    public function setAgreementId($agreement_id)
    {
        $this->container['agreement_id'] = $agreement_id;

        return $this;
    }

    /**
     * Gets data_life_unit
     *
     * @return \MyDataMyConsent\Model\DataLifeUnit|null
     */
    public function getDataLifeUnit()
    {
        return $this->container['data_life_unit'];
    }

    /**
     * Sets data_life_unit
     *
     * @param \MyDataMyConsent\Model\DataLifeUnit|null $data_life_unit data_life_unit
     *
     * @return self
     */
    public function setDataLifeUnit($data_life_unit)
    {
        $this->container['data_life_unit'] = $data_life_unit;

        return $this;
    }

    /**
     * Gets data_life_value
     *
     * @return int|null
     */
    public function getDataLifeValue()
    {
        return $this->container['data_life_value'];
    }

    /**
     * Sets data_life_value
     *
     * @param int|null $data_life_value data_life_value
     *
     * @return self
     */
    public function setDataLifeValue($data_life_value)
    {
        $this->container['data_life_value'] = $data_life_value;

        return $this;
    }

    /**
     * Gets data_fetch_frequency_unit
     *
     * @return \MyDataMyConsent\Model\DataFetchFrequencyUnit|null
     */
    public function getDataFetchFrequencyUnit()
    {
        return $this->container['data_fetch_frequency_unit'];
    }

    /**
     * Sets data_fetch_frequency_unit
     *
     * @param \MyDataMyConsent\Model\DataFetchFrequencyUnit|null $data_fetch_frequency_unit data_fetch_frequency_unit
     *
     * @return self
     */
    public function setDataFetchFrequencyUnit($data_fetch_frequency_unit)
    {
        $this->container['data_fetch_frequency_unit'] = $data_fetch_frequency_unit;

        return $this;
    }

    /**
     * Gets data_fetch_frequency_unit_value
     *
     * @return int|null
     */
    public function getDataFetchFrequencyUnitValue()
    {
        return $this->container['data_fetch_frequency_unit_value'];
    }

    /**
     * Sets data_fetch_frequency_unit_value
     *
     * @param int|null $data_fetch_frequency_unit_value data_fetch_frequency_unit_value
     *
     * @return self
     */
    public function setDataFetchFrequencyUnitValue($data_fetch_frequency_unit_value)
    {
        $this->container['data_fetch_frequency_unit_value'] = $data_fetch_frequency_unit_value;

        return $this;
    }

    /**
     * Gets data_fetch_type
     *
     * @return \MyDataMyConsent\Model\DataFetchType|null
     */
    public function getDataFetchType()
    {
        return $this->container['data_fetch_type'];
    }

    /**
     * Sets data_fetch_type
     *
     * @param \MyDataMyConsent\Model\DataFetchType|null $data_fetch_type data_fetch_type
     *
     * @return self
     */
    public function setDataFetchType($data_fetch_type)
    {
        $this->container['data_fetch_type'] = $data_fetch_type;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \MyDataMyConsent\Model\DataConsentStatus|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \MyDataMyConsent\Model\DataConsentStatus|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets approved_at_utc
     *
     * @return \DateTime|null
     */
    public function getApprovedAtUtc()
    {
        return $this->container['approved_at_utc'];
    }

    /**
     * Sets approved_at_utc
     *
     * @param \DateTime|null $approved_at_utc approved_at_utc
     *
     * @return self
     */
    public function setApprovedAtUtc($approved_at_utc)
    {
        $this->container['approved_at_utc'] = $approved_at_utc;

        return $this;
    }

    /**
     * Gets rejected_at_utc
     *
     * @return \DateTime|null
     */
    public function getRejectedAtUtc()
    {
        return $this->container['rejected_at_utc'];
    }

    /**
     * Sets rejected_at_utc
     *
     * @param \DateTime|null $rejected_at_utc rejected_at_utc
     *
     * @return self
     */
    public function setRejectedAtUtc($rejected_at_utc)
    {
        $this->container['rejected_at_utc'] = $rejected_at_utc;

        return $this;
    }

    /**
     * Gets expires_at_utc
     *
     * @return \DateTime|null
     */
    public function getExpiresAtUtc()
    {
        return $this->container['expires_at_utc'];
    }

    /**
     * Sets expires_at_utc
     *
     * @param \DateTime|null $expires_at_utc expires_at_utc
     *
     * @return self
     */
    public function setExpiresAtUtc($expires_at_utc)
    {
        $this->container['expires_at_utc'] = $expires_at_utc;

        return $this;
    }

    /**
     * Gets requested_at_utc
     *
     * @return \DateTime|null
     */
    public function getRequestedAtUtc()
    {
        return $this->container['requested_at_utc'];
    }

    /**
     * Sets requested_at_utc
     *
     * @param \DateTime|null $requested_at_utc requested_at_utc
     *
     * @return self
     */
    public function setRequestedAtUtc($requested_at_utc)
    {
        $this->container['requested_at_utc'] = $requested_at_utc;

        return $this;
    }

    /**
     * Gets requested_financial_accounts
     *
     * @return \MyDataMyConsent\Model\DataConsentRequestedAccountDto[]|null
     */
    public function getRequestedFinancialAccounts()
    {
        return $this->container['requested_financial_accounts'];
    }

    /**
     * Sets requested_financial_accounts
     *
     * @param \MyDataMyConsent\Model\DataConsentRequestedAccountDto[]|null $requested_financial_accounts requested_financial_accounts
     *
     * @return self
     */
    public function setRequestedFinancialAccounts($requested_financial_accounts)
    {
        $this->container['requested_financial_accounts'] = $requested_financial_accounts;

        return $this;
    }

    /**
     * Gets requested_documents
     *
     * @return \MyDataMyConsent\Model\DataConsentRequestedDocumentDto[]|null
     */
    public function getRequestedDocuments()
    {
        return $this->container['requested_documents'];
    }

    /**
     * Sets requested_documents
     *
     * @param \MyDataMyConsent\Model\DataConsentRequestedDocumentDto[]|null $requested_documents requested_documents
     *
     * @return self
     */
    public function setRequestedDocuments($requested_documents)
    {
        $this->container['requested_documents'] = $requested_documents;

        return $this;
    }

    /**
     * Gets requested_health_data
     *
     * @return \MyDataMyConsent\Model\DataConsentRequestedDocument[]|null
     */
    public function getRequestedHealthData()
    {
        return $this->container['requested_health_data'];
    }

    /**
     * Sets requested_health_data
     *
     * @param \MyDataMyConsent\Model\DataConsentRequestedDocument[]|null $requested_health_data requested_health_data
     *
     * @return self
     */
    public function setRequestedHealthData($requested_health_data)
    {
        $this->container['requested_health_data'] = $requested_health_data;

        return $this;
    }

    /**
     * Gets requested_identity_details
     *
     * @return \MyDataMyConsent\Model\JsonSchema|null
     */
    public function getRequestedIdentityDetails()
    {
        return $this->container['requested_identity_details'];
    }

    /**
     * Sets requested_identity_details
     *
     * @param \MyDataMyConsent\Model\JsonSchema|null $requested_identity_details requested_identity_details
     *
     * @return self
     */
    public function setRequestedIdentityDetails($requested_identity_details)
    {
        $this->container['requested_identity_details'] = $requested_identity_details;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


