<?php
/**
 * FinancialAccountType
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  MyDataMyConsent
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MyDataMyConsent\Model;
use \MyDataMyConsent\ObjectSerializer;

/**
 * FinancialAccountType Class Doc Comment
 *
 * @category Class
 * @package  MyDataMyConsent
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FinancialAccountType
{
    /**
     * Possible values of this enum
     */
    const SAVINGS_BANK_ACCOUNT = 'SavingsBankAccount';
    const MUTUAL_FUND = 'MutualFund';
    const EQUITY_SHARE = 'EquityShare';
    const NATIONAL_PENSION_SCHEME = 'NationalPensionScheme';
    const INSURANCE_POLICY = 'InsurancePolicy';
    const DEMAT = 'Demat';
    const CREDIT_CARD = 'CreditCard';
    const LOAN = 'Loan';
    const BOND = 'Bond';
    const DEBENTURE = 'Debenture';
    const DEPOSIT = 'Deposit';
    const GOVERNMENT_SECURITY = 'GovernmentSecurity';
    const INDIAN_DEPOSITORY_RECEIPT = 'IndianDepositoryReceipt';
    const INVIT = 'Invit';
    const REIT = 'Reit';
    const PUBLIC_PROVIDENT_FUND = 'PublicProvidentFund';
    const SYSTEMATIC_INVESTMENT_PLAN = 'SystematicInvestmentPlan';
    const TERM_DEPOSIT = 'TermDeposit';
    const UNIT_LINKED_INSURANCE_PLAN = 'UnitLinkedInsurancePlan';
    const RECURRING_DEPOSIT = 'RecurringDeposit';
    const ALTERNATIVE_INVESTMENT_FUND = 'AlternativeInvestmentFund';
    const CREDIT_SCORE_REPORT = 'CreditScoreReport';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SAVINGS_BANK_ACCOUNT,
            self::MUTUAL_FUND,
            self::EQUITY_SHARE,
            self::NATIONAL_PENSION_SCHEME,
            self::INSURANCE_POLICY,
            self::DEMAT,
            self::CREDIT_CARD,
            self::LOAN,
            self::BOND,
            self::DEBENTURE,
            self::DEPOSIT,
            self::GOVERNMENT_SECURITY,
            self::INDIAN_DEPOSITORY_RECEIPT,
            self::INVIT,
            self::REIT,
            self::PUBLIC_PROVIDENT_FUND,
            self::SYSTEMATIC_INVESTMENT_PLAN,
            self::TERM_DEPOSIT,
            self::UNIT_LINKED_INSURANCE_PLAN,
            self::RECURRING_DEPOSIT,
            self::ALTERNATIVE_INVESTMENT_FUND,
            self::CREDIT_SCORE_REPORT,
        ];
    }
}


