<?php
/**
 * SupportedDocumentTypeCategoryDetailsDto
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  MyDataMyConsent
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MyDataMyConsent\Model;

use \ArrayAccess;
use \MyDataMyConsent\ObjectSerializer;

/**
 * SupportedDocumentTypeCategoryDetailsDto Class Doc Comment
 *
 * @category Class
 * @package  MyDataMyConsent
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class SupportedDocumentTypeCategoryDetailsDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SupportedDocumentTypeCategoryDetailsDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'document_type_category_id' => 'string',
        'document_type_category_name' => 'string',
        'supported_documents' => '\MyDataMyConsent\Model\SupportedDocumentDetailsDto[]',
        'supported_document_provider_details' => '\MyDataMyConsent\Model\SupportedDocumentProviderDetailsDto[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'document_type_category_id' => 'uuid',
        'document_type_category_name' => null,
        'supported_documents' => null,
        'supported_document_provider_details' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'document_type_category_id' => 'documentTypeCategoryId',
        'document_type_category_name' => 'documentTypeCategoryName',
        'supported_documents' => 'supportedDocuments',
        'supported_document_provider_details' => 'supportedDocumentProviderDetails'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'document_type_category_id' => 'setDocumentTypeCategoryId',
        'document_type_category_name' => 'setDocumentTypeCategoryName',
        'supported_documents' => 'setSupportedDocuments',
        'supported_document_provider_details' => 'setSupportedDocumentProviderDetails'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'document_type_category_id' => 'getDocumentTypeCategoryId',
        'document_type_category_name' => 'getDocumentTypeCategoryName',
        'supported_documents' => 'getSupportedDocuments',
        'supported_document_provider_details' => 'getSupportedDocumentProviderDetails'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['document_type_category_id'] = $data['document_type_category_id'] ?? null;
        $this->container['document_type_category_name'] = $data['document_type_category_name'] ?? null;
        $this->container['supported_documents'] = $data['supported_documents'] ?? null;
        $this->container['supported_document_provider_details'] = $data['supported_document_provider_details'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['document_type_category_id'] === null) {
            $invalidProperties[] = "'document_type_category_id' can't be null";
        }
        if ($this->container['document_type_category_name'] === null) {
            $invalidProperties[] = "'document_type_category_name' can't be null";
        }
        if ($this->container['supported_documents'] === null) {
            $invalidProperties[] = "'supported_documents' can't be null";
        }
        if ($this->container['supported_document_provider_details'] === null) {
            $invalidProperties[] = "'supported_document_provider_details' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets document_type_category_id
     *
     * @return string
     */
    public function getDocumentTypeCategoryId()
    {
        return $this->container['document_type_category_id'];
    }

    /**
     * Sets document_type_category_id
     *
     * @param string $document_type_category_id document_type_category_id
     *
     * @return self
     */
    public function setDocumentTypeCategoryId($document_type_category_id)
    {
        $this->container['document_type_category_id'] = $document_type_category_id;

        return $this;
    }

    /**
     * Gets document_type_category_name
     *
     * @return string
     */
    public function getDocumentTypeCategoryName()
    {
        return $this->container['document_type_category_name'];
    }

    /**
     * Sets document_type_category_name
     *
     * @param string $document_type_category_name document_type_category_name
     *
     * @return self
     */
    public function setDocumentTypeCategoryName($document_type_category_name)
    {
        $this->container['document_type_category_name'] = $document_type_category_name;

        return $this;
    }

    /**
     * Gets supported_documents
     *
     * @return \MyDataMyConsent\Model\SupportedDocumentDetailsDto[]
     */
    public function getSupportedDocuments()
    {
        return $this->container['supported_documents'];
    }

    /**
     * Sets supported_documents
     *
     * @param \MyDataMyConsent\Model\SupportedDocumentDetailsDto[] $supported_documents supported_documents
     *
     * @return self
     */
    public function setSupportedDocuments($supported_documents)
    {
        $this->container['supported_documents'] = $supported_documents;

        return $this;
    }

    /**
     * Gets supported_document_provider_details
     *
     * @return \MyDataMyConsent\Model\SupportedDocumentProviderDetailsDto[]
     */
    public function getSupportedDocumentProviderDetails()
    {
        return $this->container['supported_document_provider_details'];
    }

    /**
     * Sets supported_document_provider_details
     *
     * @param \MyDataMyConsent\Model\SupportedDocumentProviderDetailsDto[] $supported_document_provider_details supported_document_provider_details
     *
     * @return self
     */
    public function setSupportedDocumentProviderDetails($supported_document_provider_details)
    {
        $this->container['supported_document_provider_details'] = $supported_document_provider_details;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


